### ISSUE TITLE
private variable leaks onto window object

### ISSUE THREAD

**Issue by cspotcode** [SteveSanderson/knockout.mapping#100]
The first line of the `fillOptions()` function was missing `var` before `options`.  Two of the QUnit tests leak variables as well, though I know that's not really a problem.

I fixed all three cases here:  8ffac4e7429473b8c2885b32340aa52824d6a72f

I'm not sure if you have any standards or conventions for pull requests, issues, integration tests, one-commit-per-feature, etc, so pardon my making a whole issue for something so tiny.  I didn't write an integration test or make a pull request but I'll be happy to do so.

**Comment by sagacity** [comment]
No, that's fine, thanks for reporting this! For major changes I would appreciate a pull request with relevant tests, but for an issue as small as this, just a heads up is enough.

No issue is too small though, so again: thanks for reporting!
