### ISSUE TITLE
toJSON slow

### ISSUE THREAD

**Issue by adriaanp** [SteveSanderson/knockout.mapping#101]
I'm using [npr's smart dirtyFlag solution](http://www.knockmeout.net/2011/05/creating-smart-dirty-flag-in-knockoutjs.html) but with the mappings.toJSON method. Using jasmine tests my tests ran quickly. But since upgrading to the latest version everything slowed dramatically down.

I don't have huge models, and I've tested on a very simple model to confirm. For my test suit of 19 specs it is taking almost a minute to run.

This looks like it is relating to the array mapping update.

**Comment by sagacity** [comment]
Can you create a reproduction scenario and put it up on jsfiddle? That would help tremendously.
Which version of the mapping plugin did you use previously?

**Comment by adriaanp** [comment]
http://jsfiddle.net/adriaanp/ssXFD/

Previous version was 2.1.2

I think I've found the problem. I've defined a method toJSON on my model, if I uncomment or rename that method everything runs normally, else it runs slow. It's looks like its calling the method recursively.

To confirm this does not happen with 2.1.2

Hope this helps

**Comment by sagacity** [comment]
Okay, can you then update your fiddle to illustrate _that_, instead of the dirty flag implementation? I'd like to see a basic version of what your toJSON is doing, if possible.

**Comment by adriaanp** [comment]
Updated http://jsfiddle.net/adriaanp/ssXFD/1/

**Comment by sagacity** [comment]
You're eventually getting a stack-overflow exception. The reason for this is that the plugin needs to call `toJSON` on your object to determine the key, but you are calling `ko.mapping.toJSON` in _your_ `toJSON` implementation as well, causing the loop.

What's the reason you are overriding `toJSON` in this way?

**Comment by adriaanp** [comment]
The framework we have created has a base class Model which for convenience has the toJSON method. It got changed later to leverage ko.mapping because some properties we want always to be excluded from the JSON.

Did not realize that JSON.stringify will actually call that method.

Will the only solution be to rename that function?

**Comment by sagacity** [comment]
Yes, you'll need to do either that or avoid calling `ko.mapping.toJSON` in your own `toJSON` method, sorry.
