### ISSUE TITLE
fromJS with create callback

### ISSUE THREAD

**Issue by adriaanp** [SteveSanderson/knockout.mapping#104]
I've got this scenario where I have default properties being set for view models, these default properties are declared on the prototype of my model. In my constructor I'm using fromJS(defaults, {}, this) to create the set of default properties.

Instantiating the model not going through the create callback my default properties gets created, but if I use a create callback only the first instance gets "mapped".

Here is a fiddle: http://jsfiddle.net/adriaanp/TcX5U/5/

**Comment by supergibbs** [comment]
That method is for mapping data to a previously mapped object to update it. I do something similar to what you want though. Add jQuery and replace line 3 in your JSFiddle with:
`$.extend(this, ko.mapping.fromJS(this.defaults));`

**Comment by sagacity** [comment]
@adriaanp Does this solve your issue? If not, feel free to reopen this ticket.
