### ISSUE TITLE
fromJS doesn't convert everything to observablearray

### ISSUE THREAD

**Issue by johnwest80** [SteveSanderson/knockout.mapping#109]
I know this is probably touched on, and might even be expected behavior for some reason I don't understand.  I've done lots of searches, though, and obviously can't figure out the magic search words to find the right results :).

I've created a fiddle to show what I'm experiencing.  When I have an object within an object and call fromJS, parts of the object is converted to observables, while other parts aren't.  The ones that aren't mean I can't replace that subobject and have the binding work correctly.  

In my model below, items is converted, the properties of the input objects are converted, but the input object itself remains POJO.  So I can't replace one input object with another and have it bind.

var model = {
    items : ko.mapping.fromJS( [{name: "abc", input: {html : "<b>abcinput</b>", val : 2} }, {name: "def", input: {html : "<b>definput</b>", val : 5} }])
};

This fiddle shows in detail.

http://jsfiddle.net/johnwest80/2Lcx9/

What am I missing?  Thanks for any help you can give.

**Comment by johnwest80** [comment]
So maybe this is an answer... in the comments it's stated that knockout mapping doesn't create observables for objects.  Shouldn't there be an option to change this, rather than have to create mappings just to make this happen?  I mean, my object graph might be pretty deep.  I don't want to have to create mappings just for this.  

Am I right that this is what I'm experiencing?  Is there a global option I'm missing to change mapping behavior?  How do I make a feature request to have this option added?  Sorry, pretty new to the github thing...

https://github.com/SteveSanderson/knockout.mapping/issues/79

**Comment by sagacity** [comment]
Right now creating the mappings is the workaround to use. If you are really interested in having this option I can certainly assist you with developing it, but for now my time to work on this is sadly severely limited. Feel very free to reopen this issue if you would like to go ahead with it.
