### ISSUE TITLE
Update mapping is not being called

### ISSUE THREAD

**Issue by dotnetwise** [SteveSanderson/knockout.mapping#111]
Look at this rather stuppid code of knockoutJS
http://screencast.com/t/luLAq97HHm

Here is a test
http://fiddle.jshell.net/NFEG6/

... and here is from your documentation (http://knockoutjs.com/documentation/plugins-mapping.html)
http://screencast.com/t/sBpGZZA03

**Comment by sagacity** [comment]
I believe this is the same as #105, I'll fix it asap.

**Comment by dotnetwise** [comment]
Exactly! So an image worths 1000 words, they say :+1:
