### ISSUE TITLE
Knockout mapping removes validation after second mapping

### ISSUE THREAD

**Issue by Mobsan** [SteveSanderson/knockout.mapping#113]
Mapping multiple datasources to multiple viewmodels (one to one).
The validation will fail in special cases. The problems appear when the second mapping is done (new datasource and new viewmodel). The validation is only failing on subobjects in an observableArray.
- If there is no second mapping, everything works fine.
- Problem occurs only on observableArrays.
- Workaround: use setTimeout() for delayed second mapping (not acceptable)

http://jsfiddle.net/Mobsan/KmyAU/5/
(See bottom of script area for options)

Is the mapping async, cant process two viewmodels at the same time? 
Is there a another way of doing this? 
Bug to fix for next version?

**Comment by sagacity** [comment]
Right now the mapping plugin does not work async since it needs to override some behavior in KO to properly handle circular dependencies. However, doing multiple mappings sequentially (without a timeout in between) should work. I'll need to check.

**Comment by lisandropuzzolo** [comment]
Hi, i proposed a temporary fix for the problem Mobsan is telling:
https://github.com/SteveSanderson/knockout.mapping/pull/123

**Comment by sagacity** [comment]
This is underway to becoming fixed, as part of #126
