### ISSUE TITLE
Feature Request: an 'observe' array

### ISSUE THREAD

**Issue by supergibbs** [SteveSanderson/knockout.mapping#114]
I came across a use case where I have more fields I want copied than observed. I propose a special array called `observe` that, when set, will create observables for those fields and copy the rest.

**Comment by supergibbs** [comment]
I started this [here](https://github.com/supergibbs/knockout.mapping). After a little more testing I'll request a pull

**Comment by sagacity** [comment]
Ah, excellent work! If you feel inclined, you can even add some additional documentation to the gh-pages (I saw you added some to readme.md, but the gh-pages may be even more generally useful).

**Comment by supergibbs** [comment]
You mean on the ko wiki? Once it's pulled in I'll do that.

**Comment by sagacity** [comment]
No, on the [gh-pages](https://github.com/SteveSanderson/knockout/tree/gh-pages) of the main knockout plugin. There is a mapping plugin documentation [page](https://github.com/SteveSanderson/knockout/blob/gh-pages/documentation/plugins-mapping.md) on there.

**Comment by supergibbs** [comment]
Committed gh-pages!
