### ISSUE TITLE
It should be possible to explicit declare none observables

### ISSUE THREAD

**Issue by AndersMalmgren** [SteveSanderson/knockout.mapping#121]
I use the mapping plugin with explicit declared ViewModels like

``` javascript
MyApp.MyViewModel = function(data) {
   this.field = ko.observable().extend({ customStuff: true });
   ko.mapping.fromJS(data, {}, this);
};
```

This way you can use computed observables and extend observables before the mapping plugin does the mapping. But I miss a good way of letting the mapping plugin know that I do not want a observable but a plain member. Observables are expensive and if two way binding isn't needed then they are not required to become observables.

I would like this synstax

``` javascript
MyApp.MyViewModel = function(data) {
   this.field = ko.observable().extend({ customStuff: true });
   this.normalField = null;
   ko.mapping.fromJS(data, {}, this);
};
```

This way in the mapping plugins logic you can do somthing similar to this (memberName == "normalField" in this pseudo code)

``` javascript
if(model[memberName] !== undefined && !ko.isObservable(model[memberName])) {
   //map without observable
} else {
   //map with observable
}
```

**Comment by sagacity** [comment]
Have you looked at the `ignore` array that you can pass in? You can use it
to ignore properties you want to map yourself.

**Comment by AndersMalmgren** [comment]
Yup, but then I need to map the member myself, this way it will be done elegant like current mapping functionality but without observable.

I think I have found the place in the mapping code that needs to be updated, so I can fork it and try it out, but I do not know all the fall pits messing with ko.mapping code :D I can do the change and you guys can code review it?

**Comment by sagacity** [comment]
Sure, you can always go and spike away. Please add appropriate unit tests,
though!

**Comment by AndersMalmgren** [comment]
Done, hope you like the change
