### ISSUE TITLE
test suite has failing tests when run against release (non-debug) of KO 2.2

### ISSUE THREAD

**Issue by drdamour** [SteveSanderson/knockout.mapping#128]
see this branch https://github.com/drdamour/knockout.mapping/tree/KOMappingAsync

i created a runner.release.html ( https://github.com/drdamour/knockout.mapping/blob/KOMappingAsync/spec/runner.release.html ) which references the release build of KO and 4 tests fail.   these are not fixed by https://github.com/SteveSanderson/knockout.mapping/pull/126 either.

Failing tests are:
- ProxyDependentObservable: dependentObservables with a write callback are passed through
- ProxyDependentObservable: dependentObservables without a write callback do not get a write callback
- ProxyComputed: dependentObservables with a write callback are passed through
- ProxyComputed: dependentObservables without a write callback do not get a write callback

**Comment by sagacity** [comment]
Thanks for reporting, I'm aware of this. It's because `hasWriteFunction` is not exported by the release build. I'm only using this in the tests, so if I can find a suitable workaround it should also work for the release build again.

**Comment by sagacity** [comment]
This is fixed in 0cfd93c3f55e07207ea7ec1b732f6b2562d047b0
