### ISSUE TITLE
Mapping arrays with duplicate values mangles the array

### ISSUE THREAD

**Issue by mrDarcyMurphy** [SteveSanderson/knockout.mapping#13]
``` javascript
var foo = ["1", "1", "1", "2", "3", "1", "2"];
var bar = ko.mapping.fromJS(foo);
console.log( ko.mapping.toJS(bar) ); // ["1", undefined, undefined, "2", "3"]
```

As you can see in the example, the first series of duplicate items in the array become undefined, and any subsequent duplicate values completely disappear. This occurs whether mapping.toJS or when binding to elements in the DOM.

Tested with knockout 1.2.1 and mapping 1.0.

**Comment by sagacity** [comment]
The result is kind of unexpected. It is by design that the mapping plugin cannot handle arrays with duplicate objects (see the `key` callback part of the mapping plugin documentation).

For an array of primitives like you have here, I guess duplicates should be allowed.

Is your use-case with an array of primitives like in your example, or are you using objects?

**Comment by mrDarcyMurphy** [comment]
The example I posted is a simplification but yeah, it matches my use case almost exactly. Here's a closer example:

``` javascript
data = {
  ...
  properties: {
    arrayKey: ["1", "1", "1", "2"]
  }
}
```

I'm grabbing a bunch of data via api, and the array that I noticed this happening on is one of a handful of properties that's stored in a serialized object. Until now we've been able to infer what we need from the length of the array and it's contents. It should be possible to rework things on the back-end and add a key, but being able to bind the existing array would be much easier for now.

**Comment by sagacity** [comment]
Ok! Well, if you have the time to create a pull request that would be highly appreciated :) Otherwise it may take a few days before I can get around to fixing it.

**Comment by mrDarcyMurphy** [comment]
Alright. I'll see what I can do.

**Comment by mrDarcyMurphy** [comment]
I haven't had a lot of time to look at this, but I've found that the culprit is line 305:

``` javascript
var index = ko.utils.arrayIndexOf(ko.utils.unwrapObservable(rootObject), item);
```

What happens is ko.utils.arrayIndexOf() returns the first matching index, which means that when the next line fires...

``` javascript
newContents[index] = mappedItem
```

...the same index gets used, so that item in the newContents array gets written over again and again. But since the mapping plugin is using [ko.utils.arrayIndexOf](https://github.com/SteveSanderson/knockout/blob/master/src/utils.js#L34) I'm not sure how to proceed.
