### ISSUE TITLE
ko.computed() does not evaluate for top level object when using mapping

### ISSUE THREAD

**Issue by artursgirons** [SteveSanderson/knockout.mapping#131]
problem - http://jsfiddle.net/rrgnK/2/

//works
        self.count = ko.computed(function () {
            return self.pages().length;
        });

//doesnt work
        self.count2 = ko.observable(0);
        ko.computed(function () {
            //looks like this is not fiering
            self.count2(self.pages().length);
        });

**Comment by sagacity** [comment]
This is already fixed in the version in `master`:
https://raw.github.com/SteveSanderson/knockout.mapping/master/knockout.mapping.js

An official release will be done soon! Thanks for reporting.
