### ISSUE TITLE
throttle issue using mapping

### ISSUE THREAD

**Issue by artursgirons** [SteveSanderson/knockout.mapping#134]
Problems is such - if I create ko.computed(..).extend({ throttle: 100 }) and computed is dependent on some observable array and observable items in that array, function is evaluated every time each item is changed in array ignoring "throttle". But interesting thing is that if I subscribe to this computed, subscribe is triggered only once (but still computed function is evaluated every time).

Problem can bee seen here - http://jsfiddle.net/dzjosjusuns/wc9ZS/2/
When I click top checkbox, each sub-checkbox is checked, and you can see at the top number of times ko.computed is called (every time +6)

In principle same example but without mapping (and working throttle) - http://jsfiddle.net/dzjosjusuns/wc9ZS/
When click top checkbox, each sub-checkbox is checked, and ko,computed is called only once (every time +1)

**Comment by oising** [comment]
If it doesn't evaluate every time, how is it going to count to 100 (your throttle limit?) before notifying dependents? It sounds like the behavior is correct, no?

**Comment by artursgirons** [comment]
no. as I understand "throttle" (and that is how it works without mapping) is I create ko.computed with throttle(100ms) that depends on some property, if this property changes 10 times in 100ms ko.computed should evaluate only once (100ms after last property update) - that seems as purpose of throttle, is it not?

**Comment by sagacity** [comment]
This is fixed in 046fce94f184a05c3cd3233c1087bf4c59673876. @dzjosjusuns Can you confirm?

**Comment by artursgirons** [comment]
Yes, great, thank you!
