### ISSUE TITLE
Why is custom update for observableArray firing twice when using mapping plugin?

### ISSUE THREAD

**Issue by Dresel** [SteveSanderson/knockout.mapping#135]
Hi,

im trying to learn and understand the great mapping plugin. When using a custom binding for an observableArray with ko.mapping.fromJS, the update is fired twice. Why is this happening?

See Fiddle for an example: http://jsfiddle.net/edNCJ/

**Comment by sagacity** [comment]
This seems to happen with arrays embedded in regular objects, I'll need to check why.

**Comment by sagacity** [comment]
Fixed in a5d14f6c463c26c11ac71d40680e61d3f21ed563.
