### ISSUE TITLE
knockout with JStree having checkboxes not updating observable array

### ISSUE THREAD

**Issue by Umar-Mukhtar** [SteveSanderson/knockout.mapping#147]
i am unable to keep track of checkbox state in observable array that contains json data mapped. Tree generates accurately but the check/uncheck does not update the observablearray of objects. please help in this regard. Provide and example

**Comment by sagacity** [comment]
I'm sorry, but you are not providing a lot of detail. Can you put up a reproduction scenario on jsfiddle.net?

**Comment by Umar-Mukhtar** [comment]
http://jsfiddle.net/ZMZ8n/

i have pasted the code, requires knockout-2.1.0.js, please add to run.
i want the state of checked/unchecked  (true/false) to be updated in the observable array, i am unable to achieve this. it works fine if i exclude the use of JSTREE

**Comment by sagacity** [comment]
This doesn't seem to be related to knockout.mapping but to knockout itself. Maybe you can post to the [Google Group](http://groups.google.com/group/knockoutjs), they should be able to help you there.

**Comment by Umar-Mukhtar** [comment]
Actually DOM manipulation is being done by the JStree which is not acceptable to knockout~ :8ball:
