### ISSUE TITLE
VisitedObjects is not being cleared at end of toJSON or toJS

### ISSUE THREAD

**Issue by technomage** [SteveSanderson/knockout.mapping#17]
The temp object visitedObjects is being left on the mapping object, which causes stale data to be used in subsequent calls to both toJSON and toJS.  It should really be deleted at the end of the call so the next call walks the view model again rather than using data from the prior call.  The parentName should also be removed at that time.

From a design point of view it would be better if the argument was not modified at all, but passed separately within the methods.

I will provide a test case when I get a minute.

**Comment by sagacity** [comment]
I just took a look and I cannot seem to reproduce this problem. Can you maybe add a failing test to `mappingBehaviors.js` that indicates the problem?

**Comment by sagacity** [comment]
I'm not getting any feedback, so I'm closing this issue for now. Feel free to reopen it!
