### ISSUE TITLE
Uncaught Error: Script error for: ko

### ISSUE THREAD

**Issue by jmogera** [SteveSanderson/knockout.mapping#174]
I am trying to integrate knockout.mapping with knockout.js and require.js. I have submitted the question on Stackoverflow but I am not getting much attention on it.

http://stackoverflow.com/questions/18925717/knockout-mapping-require-js-bug

I have tried following lot of the example posted but nothing is getting me past the error.

One thing to note in following code is that if put the module name as "ko", it complains that "knockout" is not there, and if I set the module name to "knockout" it complains that "ko" is not there.
requirejs.config({
    "baseUrl": "../Scripts/app/contractor",
    "paths": {
        "app.index": "app.index",
        "knockout": "//cdnjs.cloudflare.com/ajax/libs/knockout/2.2.1/knockout-min",
        "mapping": "//cdnjs.cloudflare.com/ajax/libs/knockout.mapping/2.3.5/knockout.mapping",
        "knockout.bindings": "../../lib/knockout.bindings",
        "fu": "../../lib/jquery.fineuploader-3.8.0",
        "s2": "../../lib/select2",
        "jquery": "//code.jquery.com/jquery-latest.min",
        "jqueryui": "//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min",
        "moment": "../../lib/moment.min",
        "toastr": "../../lib/toastr"
    },
    "shim": {
        'mapping': {
            deps: ['knockout'],
            exports: 'mapping'
        }
    }
});

Please advice!

**Comment by eelkevdbos** [comment]
Hi,

I ran into this problem too. The solution to it all: _use the mapping variable instead of the ko variable_

``` js
define(['knockout', 'mapping'], function(ko, mapping) {
    //this is the toJSON method from the plugin
    console.log(mapping.toJSON({test:'test'}));
    //this is the knockout native toJSON method
    console.log(ko.toJSON({test:'test'});
});
```

Regards!

**Comment by jmogera** [comment]
I am using "ko" to define the module name, and i get "knockout" can't be found. If i use "knockout" as the module name. I am getting "ko" not found 

requirejs.config({
    baseUrl: "../../Scripts/app/",
    paths: {
        "ko": "//cdnjs.cloudflare.com/ajax/libs/knockout/3.0.0/knockout-min",
        "knockout.validation": "../../../../lib/knockout.validation",
    },
    shim: {
        "knockout.validation": ["ko"],
        'mapping': {
            deps: ['ko'],
            exports: 'mapping'
        }
    }
});

require(["ko", "mapping"], function (ko, mapping) {
    //manually set the global ko property
    window.ko = ko;

```
//then bring in knockout validation
require(["knockout.validation"], function () {
    ko.validation.configure({
        insertMessages: false,
        decorateElement: true,
        errorElementClass: 'error'
    });

    require(["main"], function (bs) { bs.run(); });
});
```

});

**Comment by jmogera** [comment]
Actually got it work based on this article:
http://www.autogenerated.com/2012/09/knockout-requirejs-amd-module-name.html
