### ISSUE TITLE
Mapping doesn't work when properties listed in different order

### ISSUE THREAD

**Issue by mcintyre321** [SteveSanderson/knockout.mapping#203]
I have a demo where a mapping is repeatedly applied. If the properties of the data being mapped aren't listed in the same order as before, ko fails to bind correctly.

http://jsfiddle.net/mcintyre321/690rfud0/6/

To demo, hit the button in the fiddle. On the third click it should update to show the third data object, but it won't. Switching the 3rd data item for the commented version will make it start working.

I am trying to map different objects structures into the viewmodel, but alas, this is preventing me.

**Comment by crissdev** [comment]
@mcintyre321 The reason why your demo fails is because the property `thirdTypeProperty` is not yet defined on the `viewModel` when `type` property is updated through `ko.mapping.fromJS`. Changing the order of the properties does fix this problem.

Updated example http://jsfiddle.net/690rfud0/11/
(Check browser's console)

**Comment by mcintyre321** [comment]
Thanks for the answer, makes sense - I think I was trying to get ko.mapping to do something it wasn't designed for (dynamically add/remove properties on the target viewmodel).

I'm thinking about writing a plugin to apply jsonpatch documents to a knockout model to achieve what I'm after - unless you happen to know of any plugins that might do the same?

**Comment by crissdev** [comment]
I know about http://coderenaissance.github.io/knockout.viewmodel/ but I don't use it, so I really can't say it has what you're after. But if you're implementing a new plugin I would be intrested to know about it :+1:

**Comment by mcintyre321** [comment]
I'll keep you posted. There are [lots](http://jsfiddle.net/mcintyre321/d3zH7/) of [interesting](http://jsfiddle.net/mcintyre321/hf65q12v/) things to be [done](http://jsfiddle.net/mcintyre321/304essdv/) with KO!
