### ISSUE TITLE
toJSON method clings to the first "" or false found while parsing

### ISSUE THREAD

**Issue by luisreyes** [SteveSanderson/knockout.mapping#21]
http://stackoverflow.com/questions/6858145/knockout-mapping-fromjs-of-arrays-containing-false-replaces-empty-strings/

Seems like the toJSON method clings to the first ""(empty string) or false found in the object and places this found value through out the rest of the object where ever it finds either a "" or a false.

A better visual of this can be seen here http://jsfiddle.net/5HhMn/

In the example try changing the first "" to a false and see it propagate to the other values.

**Comment by sagacity** [comment]
I'll try to take a look today or tomorrow, thank you for the reproduction case!
