### ISSUE TITLE
Mapping options not used in UpdateFromJS

### ISSUE THREAD

**Issue by jabrown85** [SteveSanderson/knockout.mapping#22]
I've run into what seems to be a bug.  I've put an example [here](http://jsfiddle.net/KSvCu/8/).  It appears as though the mapping options are not being executed when running the UpdateFromJS method of the mapping plugin.

**Comment by sagacity** [comment]
jsFiddle is down at the moment, so I can't check, but could you take a look at the experimental branch here and try that instead:
http://raw.github.com/SteveSanderson/knockout.mapping/updatecallback/knockout.mapping.js

The 'updateFromJS' callback is removed, you can just use multiple calls to 'fromJS' instead.

**Comment by jabrown85** [comment]
Thanks Roy, that experimental branch seems to work as expected.  The jsFiddle is back up as well if you care to see the issue on the main branch.  I've updated using your experimental branch [here](http://jsfiddle.net/KSvCu/9/) to show you how I expect it to work.

**Comment by sagacity** [comment]
Okay! I plan to do this new release (2.0) quite soon. Once you upgrade, you should be fine.
In the meantime the branch has changed from "updatecallback" to "2.0". I have updated your fiddle:
http://jsfiddle.net/KSvCu/10/

Please let me know if there is anything else that needs to be done, in the meantime I'll close this issue (just reopen it, if you want).
