### ISSUE TITLE
Incremental array updates

### ISSUE THREAD

**Issue by jpc** [SteveSanderson/knockout.mapping#27]
They are broken in 2.0:
https://github.com/SteveSanderson/knockout.mapping/commit/5199587f57de3faf3daeda0c09cc44d71e85ac76#commitcomment-579665

**Comment by jpc** [comment]
It seems like just removing the unwrap in this line does not break anything but my model is really simple so I am not testing any advanced features.

**Comment by sagacity** [comment]
Oh :(

Would it be possible for you to create a pull request that fixes this behavior? I am away at the moment and don't immediately have the time to take care of this.
