### ISSUE TITLE
Bug when using integer values and checkboxes

### ISSUE THREAD

**Issue by andreialecu** [SteveSanderson/knockout.mapping#30]
I found an issue when mapping a JS array that contains numeric values when used with a foreach template and checkboxes.

It only seems to happen in IE and Google Chrome.

The checkbox doesn't seem to accept the first click, it only works on the second click. After the second click it works properly all the time.

It's pretty hard to explain so here's a jsfiddle with it happening.

http://jsfiddle.net/ccCAP/1/

If the values are changed from being numeric to strings (aka "1" instead of 1) the checkbox works properly.

I'm not sure if this is a knockout bug or knockout.mapping bug, but knockout by itself seems to work fine with numeric values in arrays:

http://jsfiddle.net/gFGn6/1/

**Comment by andreialecu** [comment]
Actually, it's a knockout observable issue. In the second (working) example, if you change id: 1 to id: ko.observable(1) it behaves the same.

So, I'm going to guess that fixing https://github.com/SteveSanderson/knockout/pull/129 will fix this as well.

**Comment by sagacity** [comment]
Good to hear!

**Comment by oliverjanik** [comment]
This is not fixed. Still bugged with checkboxes and radios.
