### ISSUE TITLE
Array mapping error

### ISSUE THREAD

**Issue by rosieks** [SteveSanderson/knockout.mapping#32]
Hi, I have following code that is incorrect mapped:

var obj = {}, obj2 = {};
var x = [obj,obj2];
var y = { o: obj, x: x };

var z = ko.mapping.fromJS(y);

Unfortunately z.x()[0] is undefined. I notice that that happend because of the following calling updateViewModel with undefined mappedRootObject.

485: mappedItem = ko.utils.unwrapObservable(updateViewModel(undefined, item, options, parentName, mappedRootObject, fullPropertyName));

Then in update viewModel is the following line that returns that undefined:

303: if (visitedObjects.get(rootObject)) return mappedRootObject;

**Comment by sagacity** [comment]
Does this also happen when the objects contain any properties? I'm having a hard time reproducing this.
Maybe you can put up a jsfiddle illustrating a more detailed use case?

**Comment by rosieks** [comment]
Hi - this also happen when the objects contain some properies.
http://jsfiddle.net/VYY3t/1/ 
In this example you see alert with first message, that comes from JS Object but second message is not appeare because of JavaScript error.

**Comment by sagacity** [comment]
Yes, I'm seeing it too, now. Thanks for the repro!

**Comment by sagacity** [comment]
I think the bug is solved. I have updated your fiddle to use the development release:
http://jsfiddle.net/VYY3t/2/

Please let me know if it is fixed and close the issue.
