### ISSUE TITLE
Create method in mappings receive meaningless options.parent for observableArray properties

### ISSUE THREAD

**Issue by bikeshedder** [SteveSanderson/knockout.mapping#33]
When mapping arrays, options.parent is set to an observable containing an empty array regardless of the jsObject or target parameter. Normal properties receive the target model as options.parent.

It would be great if the create method would always receive the target model regardless of the type of property being mapped.

Use case: Mappings where access to the target model is required while mapping array elements.

**Comment by sagacity** [comment]
The update callback already receives the target, so you can specify that as a temporary workaround. The update callback is called immediately after the create, and also during any updates.

It should not be a problem to add the target to the create callback as well, though. I'll see what I can do.

**Comment by sagacity** [comment]
Could you maybe provide a jsfiddle that illustrates in more detail what you want to do (and how you would expect to be able to do it)?

**Comment by bikeshedder** [comment]
http://jsfiddle.net/ZwhSV/1/

In order to see what is really happening you should put some console.log statements inside the create and update functions. You should easily see that the parent is always pointing to an empty array - regardless of the previous content of Bag.items.

I just opened issue #35 which is slightly related to this.
