### ISSUE TITLE
Root-level mapping issue

### ISSUE THREAD

**Issue by matb33** [SteveSanderson/knockout.mapping#34]
I've run into an issue where when calling ko.mapping.fromJS a second time around, my browser crashes.  I haven't had time to understand enough of what's going on but managed to get it working with this change at line 173

```
    // Is there only a root-level mapping present?
    if ((options.create instanceof Function) || (options.update instanceof Function) || (options.key instanceof Function) || (options.arrayChanged instanceof Function)) {
        if (!options.hasOwnProperty("")) {
            options = {
                "": options
            };
        }
    }
```

Notice the !options.hasOwnProperty("").  On the second call to fromJS, I'd get an infinitely recursing options with an empty property name, which was causing the crash.

I'm not sure if this was the correct fix, but I'm passing it along in case it does make sense to you.

**Comment by sagacity** [comment]
Thanks for the workaround. In order for me to apply it, I would prefer to get a bit more insight in what was causing the problem. Could you create a jsfiddle containing a small reproduction scenario that causes the crash?

**Comment by matb33** [comment]
http://jsfiddle.net/matb33/fXHus/16/

Hope this helps

**Comment by sagacity** [comment]
Yes, it does. I'll try to narrow it down some more and hopefully get to the root cause.

**Comment by sagacity** [comment]
@matb33: I have updated your fiddle with a development release. Can you confirm it is okay for you now?

http://jsfiddle.net/fXHus/17/

**Comment by matb33** [comment]
Works perfectly both in the jsfiddle and in my own current application.
Nice work, and thank you for such a speedy resolution!
