### ISSUE TITLE
Latest Build Broken? Or Installation Issue?

### ISSUE THREAD

**Issue by busticated** [SteveSanderson/knockout.mapping#4]
With your console open, check out: http://jsfiddle.net/3t4yA/1/ 

I'm getting an error ("Result of expression 'ko.a.c' [undefined] is not a function.") with what appears to be a pretty well-bounded test case taken directly from the documentation.

Is there another simple way to confirm the plugin is installed properly?

**Comment by sagacity** [comment]
This was a minification issue, solved by Steve Sanderson's last commit.
