### ISSUE TITLE
Mapping fromJS should support plain arrays

### ISSUE THREAD

**Issue by shawnwildermuth** [SteveSanderson/knockout.mapping#40]
Looks like the fromJS expects the root object to be an object. I very ordinarily want to take:

var data = [{name = "", id = ""}, {name = "", id = ""}, ];
var model = ko.mapping.fromJS(data);

But this always returns an empty array. I shouldn't have to wrap it in an object just to get this to work.  This should return an observable array of the inner objects.

**Comment by jamesfoster** [comment]
This issue should be closed.

Assuming you're using the correct syntax that works fine.

``` javascript
var data = [{name: "", id: ""}, {name: "", id: ""}];
var model = ko.mapping.fromJS(data);
```

model becomes an `observableArray`, and both name and id are `observable`.

**Comment by sagacity** [comment]
@shawnwildermuth : Can you confirm?
