### ISSUE TITLE
ko.mapping.fromJS(data, self) doesn't work after reset

### ISSUE THREAD

**Issue by dotnetwise** [SteveSanderson/knockout.mapping#46]
<input type="reset" />

After the form is reset reloading the data back from server by calling ko.mapping.fromJS(data, self) where self is the viewModel and data is the new json, will do the same as pressing reset again instead of loading updated data from server.

Any advices?

**Comment by sagacity** [comment]
Can you create a small reproduction scenario and put it up on jsfiddle?

**Comment by dotnetwise** [comment]
Have you tried to reset "checkboxes" ?
