### ISSUE TITLE
Documentation Bug: array → copy

### ISSUE THREAD

**Issue by schinckel** [SteveSanderson/knockout.mapping#47]
From the KO website:
### Copying certain properties using “copy”

When converting your view model back to a JS object, by default the mapping plugin will create observables based on the rules explained above. If you want to force the mapping plugin to simply copy the property instead of making it observable, add its name to the “copy” array:

```
var mapping = {
    'array': ["propertyToCopy"]
}
var viewModel = ko.mapping.fromJS(data, mapping);
```

Fairly sure that 'array' should be 'copy'.

**Comment by jamesfoster** [comment]
This has been fixed. This issue can be closed
