### ISSUE TITLE
Have doubts, but...

### ISSUE THREAD

**Issue by baio** [SteveSanderson/knockout.mapping#48]
Hi!

Doesn't it make sence to check before line 371 (// For non-atomic types, visit all properties and update recursively //) if the property alreday has been mapped by updateCallback (line 365)? And if so , not map these properties, since it is supposed that they already have been mapped by custom update? 

The solution - add line 371

 if (!hasUpdateCallback()) {

**Comment by sagacity** [comment]
Hi baio, the current assumption of the plugin is that the 'update' callback is mostly used to handle updates of properties that were added in a 'create' callback (i.e. properties not handled by the mapping plugin).

I agree that is would be more 'correct' to ignore the properties affected by the 'update' callback. But do you have a suggestion for how to detect which properties were affected by the 'update'?

**Comment by baio** [comment]
Hi! My assumption is that if you use 'update' you must update all fields, hence nested fields shouldn't be mapped by plugin.

**Comment by sagacity** [comment]
That is not currently the case, but I agree it would match the semantics of 'create'. It might be worth adding your oneliner to change the behavior.
