### ISSUE TITLE
Consider switching from Closure Compiler to UglifyJS

### ISSUE THREAD

**Issue by domenic** [SteveSanderson/knockout.mapping#53]
For something of `knockout.mapping`'s relatively-small size and complexity, I think Google Closure compiler is causing too much pain for not enough gain. The whole `ko.exportSymbol` business is unfriendly to new developers, and buys nothing since we are keeping private all non-exported functions. Only simple optimizations are used anyway.

UglifyJS is more or less the gold standard among people not using Closure's advanced optimizations. It's easy to use on Node, which is now cross-platform.

The relative sizes are:

```
Compiler         | minified | gzipped
-------------------------------------
UglifyJS         | 9667     | 3006
Closure Compiler | 8827     | 2940
```

Just something to think about :)

**Comment by sagacity** [comment]
As always, you are certainly welcome to submit a pull request :)

Seriously though, I have zero problems with switching to UglifyJS, but it's fairly low-priority now since everything is working fine as it currently stands.
