### ISSUE TITLE
Attach a single Js Object back to a mapped parent causes browser crash

### ISSUE THREAD

**Issue by jonswaino** [SteveSanderson/knockout.mapping#55]
I'm creating a list of items which are mapped using the mapping plugin. However, I want to be able to 'attach' or copy a single object back to the mapped object inside an observableArray.  Effectively, it is used where there is a list of items, and an edit dialog is shown for the item.  When clicking 'ok' the data should map back to the source.

I have a _very_ simple jsFiddle, but this is crashing the browser:
http://jsfiddle.net/5J9aL/8 

I thought maybe using the mapping options to map the actual object inside the array might fix the problem, but no luck:
http://jsfiddle.net/RJqdD/1

On further inspection: extendObject seems to be getting into a recursive endless loop.  Can anyone check this for me to see if there is a resolution?

**Comment by sagacity** [comment]
You can fix this by not using `ko.toJS` but using `ko.mapping.toJS` instead. I have updated the fiddle. If you still run into issues, please feel free to reopn the issue.

http://jsfiddle.net/5J9aL/9/
