### ISSUE TITLE
foreach not rendering as quickly as it could

### ISSUE THREAD

**Issue by luv2code** [SteveSanderson/knockout.mapping#59]
I have a coworker that's always going on about how backbone is god's gift, and that I'm retarded for using knockout.
Today, he sent me this:
http://fiddle.jshell.net/ntMdB/139/

it's not apples-to-apples because he's using knockout to setup a bunch of two-way bindings for a one-way view.
So I modified it so that the only thing observable is the array.  But the only way I could get it to render any faster is to mess with the item order.
http://fiddle.jshell.net/ntMdB/151/

if i do an array.reverse, it's the same speed as his:
http://fiddle.jshell.net/ntMdB/157/

How can I get the speed of 151 with the same rendering result of 139 and 157?

**Comment by sagacity** [comment]
This is actually related to Knockout itself, not the mapping plugin. Feel free to open an issue there. Having said that, the new release is already quite a bit faster than when you originally opened this issue :)
