### ISSUE TITLE
Calling ko.mapping.fromJS() inside a ko.computed cause endless loop

### ISSUE THREAD

**Issue by greenlaw110** [SteveSanderson/knockout.mapping#60]
Here is the source code:

``` javascript
if (!ui.loadSubscriptions) ui.loadSubscriptions = ko.computed(function() {
    var client = data.curClient();
    if (!client.subscriptions) {
        $.ajax({
            url: '/data/client/subscriptions',
            dataType: 'json',
            async: false,
            data: {id: client._id()},
            success: function(subscriptions) {
                // ! the following statement cause the entire function been
                // evaluate again and the ajax call will be executed again
                // and so forth the mapping call. It generates an endless
                // loop
                client.subscriptions = ko.mapping.fromJS(subscriptions);
            },
            error: function(jqXHR, textStatus, errorThrown) {
                _.error("error load client subscriptions");
                throw errorThrown;
            }
        });
    }
});
```

**Comment by thvd** [comment]
I think it shouldn't be an computed observable, but a normal anonymous function.

**Comment by greenlaw110** [comment]
No I need it to be computed, because I want the ajax loading be run each time I changed the current client

**Comment by thvd** [comment]
Then you need to subscribe on the current client. http://knockoutjs.com/documentation/observables.html#explicitly_subscribing_to_observables
Because the $.ajax method is asynchronous.

**Comment by greenlaw110** [comment]
Yes, inside the function I have `var client = data.curClient();`, that statement makes the computed function get called everytime the curClient changes

**Comment by thvd** [comment]
No, you should subscribe, as mentioned on the page i linked for you, on the data.curClient like this:

```

data.curClient.subscribe(function(newValue) {
    // this function will every time executed when data.curClient changes.
    // put here your ajax request, like the code you had in your first message in the ko.computed block.

});


```

**Comment by greenlaw110** [comment]
I read that. What's difference between it and invoking the observable in a ko.computed ? I was always using ko.computed without any problem until I met this issue

**Comment by thvd** [comment]
We are actually talking about the way how to implement. But maybe it's a good idea to create a fiddle? So we can dig into your actually problem (an infinite loop) a bit better.

**Comment by sagacity** [comment]
No reply for over a month. Please feel free to reopen this issue!

**Comment by hanxuema** [comment]
hi greenlaw110

Did you find the reason why this issues was happening and what you did to solve the issue? Can you please share?

Regards
