### ISSUE TITLE
ko.mapping.ToJSON () question 

### ISSUE THREAD

**Issue by pierol** [SteveSanderson/knockout.mapping#68]
Hi Roy, i have a new behavior with the latest mapping plugin. I've made this fiddle example http://jsfiddle.net/pierol/RtJaH/1/ example that reproduce the problem. I create a viewmodel with a ko.mapping.fromJS(data1), where data1 is a JSON object obtain from a AJAX call. In this object there is a void Immagini array that become an observable array when i call the fromJS function. Then i add to this array an element with the viewModel.Immagini.push(newelement) when i press the add button, but when i made the ko.mapping.toJSON(viewmodel), in the Immagini array there is a void element: {}. Is that an expected behavior of the plugin or this is an issue ?

**Comment by sagacity** [comment]
Yes, there are a few issues with the latest release, so I reverted the last commit. Can you try the version that's available now (2.1.0, also on nuget or here: https://github.com/SteveSanderson/knockout.mapping/tree/master/build/output)

**Comment by pierol** [comment]
Yes, it works. Thank you again.

**Comment by DzenisevichK** [comment]
Expected behaviour of `ko.mapping.toJSON(viewmodel)` is to return empty `Immagini` array (as was before `ko.mapping.fromJS`) so both versions don't work correct or?

**Comment by DzenisevichK** [comment]
I think this issue should be reopened.

**Comment by sagacity** [comment]
Expected behavior is that the new element is retained. Otherwise you would never be able to add a new element to a mapped array and send it back to the server.

**Comment by DzenisevichK** [comment]
What about adding a new property to a object after `ko.mapping.fromJS`?

**Comment by sagacity** [comment]
That is different, properties you add later are considered to be part of your viewmodel, not of your original data. However, since `Immagini` _is_ part of the original data, all items added to it are also considered part of the data.

**Comment by DzenisevichK** [comment]
Ok, what about little more complex example:

```
var viewModel = ko.mapping.fromJS({
    a: {
        b: "",
        c: ""
    }
});
viewModel.d = {};
viewModel.a.e = "";
var data = ko.mapping.toJS(viewModel);
```

Which properties are considered as part of `data`?

**Comment by sagacity** [comment]
Only `a.b` and `a.c`, but I think that due to way nested options are in 2.1.0 (so without your fixes), it will also include `a.e`.

**Comment by sagacity** [comment]
So I'd really like to merge your changes in, but then (for now) the "include"/"ignore" syntax would have to be backwards compatible. In the example above, saying: `include: ['e']` should also include `a.e`. Then, for a next release (3.0) we would implement it properly as discussed in #65. Is that okay with you?

**Comment by DzenisevichK** [comment]
What if data may have optional `d` property that may be set on client side and returned to server... There are many variants...
We cannot know here which properties are expected as data which are not. So we need pass options as additional info and I think that saving options in viewModel after `ko.mapping.fromJS` is not correct.

**Comment by sagacity** [comment]
In the case where a property is only ever set on the client-side, you should add it to the `include` parameter.
