### ISSUE TITLE
toJS - Update existing model

### ISSUE THREAD

**Issue by kakone** [SteveSanderson/knockout.mapping#75]
it would be nice if we could update all the properties of an existing model with the toJS function (like the fromJS function) :
exports.toJS = function (rootObject, options, target)

**Comment by sagacity** [comment]
How do you mean 'update'? The only purpose of `toJS` is to convert a viewmodel back to look like the original JS object you put in.

**Comment by kakone** [comment]
In my case, my model contains more fields than the viewmodel.
I create the viewmodel manually and I use the function ko.mapping.fromJS(jsObject, inputOptions, existingViewModel) to update the values of the viewmodel properties from my jsObject.
So, I want to do the inverse operation with the toJS function : to update the values of some properties of an existing model with the same properties of the viewmodel.

**Comment by sagacity** [comment]
Can you maybe split your viewmodel in two parts? One part that is the original data that you map using `fromJS` and back with `toJS` and a second part that you don't want to overwrite.

E.g.:

var viewModel = {
  mapped: ko.mapping.fromJS(sourceData),
  otherData: {},
  moreOtherData: {}
};

And then you would use `toJS` only for the `mapped` object.

**Comment by kakone** [comment]
Yes, I can do what you suggest but I want to keep some independence between my view and my model.
In your case, if the model is modified (a field is renamed for example), you must modify the view. In my case, I change the mapping between the model and the viewmodel.

In my project, I don't use the ko mapping plugin to create automatically the viewmodels but to avoid some repetitive tasks (to update the values of some properties).

**Comment by sagacity** [comment]
Sure, I understand the problem. But it was simply never part of the design of the plugin to handle this scenario.
You are certainly welcome to add this functionality, though. :)
