### ISSUE TITLE
ko.mapping.toJS generates empty array items

### ISSUE THREAD

**Issue by gonglei** [SteveSanderson/knockout.mapping#76]
With knockoutjs mapping plugin 2.1.2, I found that ko.mapping.toJS generated empty array items if viewmodel (with an array element) is updated with ko.mapping.fromJS and the new array element's length is longer than the old one.

My initial data mapped is:

var initData = {text: 'Some Text', 
                arr: [{key: 1, value: 'a'}, 
                      {key: 2, value: 'b'}]};

Then I updated view model with a new object:

var newData = {text: 'Changed Text', 
                arr: [{key: 1, value: 'aa'}, 
                      {key: 12, value: 'bb'},
                      {key: 13, value: 'cc'}]};

After that I called ko.mapping.toJS(), I found that the 3rd array item is an empty object. I am not sure if this is a bug or I missed something. Another thing I noticed is, it happens only first time I update data. If I update view model with initData then newData again, the result is correct. http://jsfiddle.net/xgPSq/

**Comment by wjbryant** [comment]
I had a similar issue and the solution was to use the `create` callback for the array items. You can see the discussion [here](https://github.com/SteveSanderson/knockout.mapping/issues/74).

I modified your example to use the `create` callback and it seemed to fix the problem: http://jsfiddle.net/xgPSq/9/
