### ISSUE TITLE
Empty children with toJSON

### ISSUE THREAD

**Issue by AndersMalmgren** [SteveSanderson/knockout.mapping#78]
I have a prototype main model and a prototype children model.
The items that were originally created with the mapping plugin are serialized to JSON correctly, but the item that were added to the array using push(new ChildViewModel()) are just empty JSON objects {}.

http://jsfiddle.net/699YH/

**Comment by sagacity** [comment]
You will need to add that item by using the mapping plugin as well.

I have updated the fiddle to illustrate:
http://jsfiddle.net/699YH/2/
