### ISSUE TITLE
mapping plugin doesn't generate an observable for a empty object

### ISSUE THREAD

**Issue by keithn** [SteveSanderson/knockout.mapping#79]
following are some tests, the one with null works, the one  with {} doesn't

``` javascript
test('mapping a blank object creates a observable', function () {
    var data = {
        a : {}      
    };

    var mapped = ko.mapping.fromJS(data);  
  equal(ko.isObservable(mapped.a), true);
});

test('mapping a null object creates a observable', function () {
    var data = {
        a : null        
    };

    var mapped = ko.mapping.fromJS(data);  
  equal(ko.isObservable(mapped.a), true);
});
```

**Comment by sagacity** [comment]
This is by design, the mapping plugin only creates observables from non-object types. However, if you want to override this behavior you can specify a `create` callback in the mapping options to perform the mapping of a specific part of the object tree yourself.
