### ISSUE TITLE
mapping doesn't serialize entire object structure.

### ISSUE THREAD

**Issue by keithn** [SteveSanderson/knockout.mapping#80]
related to this stackoverflow question  http://stackoverflow.com/questions/10891082/knockout-mapping-seems-to-break-value-binding-for-dropdown/10891540

Here is some mapping that doesn't seem to result in the right json?

The first test doesn't work, the second one does.

``` javascript
test('mapping then turrning to json serializes entire object structure', function () {
    var data = {
    a : null,
    b: [{ x: 1, y: 2}, { x: 1, y: 2}]        
  };

  var mapped = ko.mapping.fromJS(data);

  mapped.a(mapped.b()[0]);

  equal(mapped.a().x(), 1);

  var s = ko.toJSON(ko.mapping.toJS(mapped));

  equal(s, '{"a":{"x":1,"y":2},"b":[{"x":1,"y":2},{"x":1,"y":2}]}');

});


test('manual binding then turrning to json serializes entire object structure', function () {
    var data = {
    a : null,
    b: [{ x: 1, y: 2}, { x: 1, y: 2}]        
  };

  var model = {}
  model.a = ko.observable(data.a);
  model.b = ko.observableArray(data.b);

  model.a(model.b()[0]);

  var s = ko.toJSON(ko.mapping.toJS(model));

  equal(s, '{"a":{"x":1,"y":2},"b":[{"x":1,"y":2},{"x":1,"y":2}]}');

});
```

**Comment by sagacity** [comment]
Please use `ko.mapping.toJSON` instead of `ko.toJSON`. Does that give you the expected output?

**Comment by jerryclinesmith** [comment]
Using ko.mapping.toJSON still doesn't seem to work correctly: http://jsfiddle.net/JerryClinesmith/hsx7P/

**Comment by sagacity** [comment]
I have updated the fiddle to use mapping plugin 2.1.0 instead of 2.1.2. Does that help?
http://jsfiddle.net/hsx7P/3/

**Comment by jerryclinesmith** [comment]
Yes, that's working as expected with that version.

**Comment by sagacity** [comment]
Okay, then I recommend you keep using that version. There's a number of issues with the 2.1.2 release so I'll probably revert the code back to 2.1.0 for the time being.

I'm closing the ticket for now but feel free to reopen it if any problems remain.
