### ISSUE TITLE
2.2.0 -> getItemByKey throwing error

### ISSUE THREAD

**Issue by antmrdevlabs** [SteveSanderson/knockout.mapping#84]
Since 2.2.0 the method getItemByKey is throwing an error because the passed-in key is "null". This happens when currentArrayKeys and newArrayKeys have items, but with an "null" value. I do not know, why this happens.

**Comment by sagacity** [comment]
I did make a few changes in that area to boost performance. Do you have a repro case you can put up on jsfiddle that shows this behavior?

**Comment by antmrdevlabs** [comment]
Hi, I don't know how to put this in a jsfiddle. What i've found out so far is, that i have an object with a property called FormContents which is an array and which key-values are null. So when the mapping plugin is running into this property it quits.

FormContents: [null, null]
0: null
1: null

Does it help you?

**Comment by sagacity** [comment]
So your original data already has `null` keys?

**Comment by antmrdevlabs** [comment]
yes, you're right, thanks for the hint :) . i changed my code to not add null-values into the array, and now it's working fine (-> empty array, FormContents = [ ]), so it was an error on my side.

the issue only occurs if there is an array, that includes null keys. i do not know, if it is a good idea to check for null-keys in the mapping plugin?!

**Comment by sagacity** [comment]
Yes, it might make sense to add some checks. I'll try to add tests for that. I'll close the issue for now, if you have any remaining problems please feel free to reopen it!

**Comment by Bouke** [comment]
Today I ran into the same problem while updating an array with nullable values. I've created a jsfiddle for you to reproduce: http://jsfiddle.net/a654A/1/.

**Comment by sagacity** [comment]
Thanks for the repro! This should now be fixed in 5075bb9f64e8bfebc1ef5158e79382db25b13c19.

**Comment by Bouke** [comment]
Bedankt, however there is something strange going on. All is fine with the debug build, but the normal build does not work when using a `key` function on the parent object. Fiddles: [debug build](http://jsfiddle.net/a654A/2/) and [normal build](http://jsfiddle.net/a654A/3/).

**Comment by sagacity** [comment]
Ah, minification troubles :( I'll take a look.

**Comment by sagacity** [comment]
Apparently the minified version didn't get rebuilt. It should be okay now.
