### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by DavidDeSloovere** [SteveSanderson/knockout.mapping#85]
Can't seem to find a change log.
I'm very cautious when nuget says there's an update (2.2 now) and I don't know if my app will break or not (using 2.0). But if only the minor version is update, it should not break right. But still, change log would be great.

**Comment by sagacity** [comment]
Good point. I'm trying to follow semantic versioning though, so going from 2.0 to 2.2 there should be no breaking changes, only performance improvements and the like.

Also, when you clone the git repo there is a full unit test suite that you can run to confirm everything is okay.

Having said that, a changelog could certainly still be useful. What do you consider the best way to distribute the changelog? Simply as part of the nuget?

**Comment by DavidDeSloovere** [comment]
I expect it to find when I hit the 'project site' link. Which currently leads to http://knockoutjs.com/documentation/plugins-mapping.html, so either on that page (which still says v2.0 btw) or a clear link to the change log, both are good really.
If it's a link to somewhere elseo, then maybe on the github wiki?

The 'missing change log'-feeling I get isn't just for this project, it's more related to all nuget packages. So I might post that on the nuget forum to see what other people are thinking.

**Comment by sagacity** [comment]
For now, I'll probably add a `history.md` to this repo.
