### ISSUE TITLE
ko.mapping.toJS generates empty array elements

### ISSUE THREAD

**Issue by tuscland** [SteveSanderson/knockout.mapping#87]
Hello,

I am having an issue that seems to be introduced with the 2.2 release.  The code is working fine with version 2.1.2, but is broken with versions 2.2.0 or 2.2.1.

My view model uses an observable array and defines a mapping with a `create:` function to instanciate the child view models.

Children view models loaded from existing data properly persist after the call to `toJS` (i.e. they are correctly generated).  However, children that were instanciated after the view model is loaded, are rendered as empty object in the resulting call to `toJS`.

Providing a `key:` function for the collection does not solve the issue.

More information: I am using latest version of Chrome, and the ko.validation plugin.

Suggestions are welcome!

Best,
Camille

**Comment by sagacity** [comment]
Can you create a simple reproduction scenario using jsfiddle?

**Comment by tuscland** [comment]
Hi Roy, thank you for coming back to me.
Here is a test case that exactly demonstrates my issue: http://jsfiddle.net/pbvtH/9/

The output should be exactly the initial data:

``` JSON
{"employees":[{"name":"John Doe","position":"CEO","age":42},{"name":"Margaret Field","position":"CFO","age":39}],"companyName":"ACME"}
```

Now, click the "Add Employee" button.  The result is:

``` JSON
{"employees":[{"name":"John Doe","position":"CEO","age":42},{"name":"Margaret Field","position":"CFO","age":39},{}],"companyName":"ACME"}
```

(notice the empty object at last position)

**Comment by tuscland** [comment]
... and another fiddle using ko.mapping v2.1.2 (results are correct):

http://jsfiddle.net/aEH3c/1/

**Comment by sagacity** [comment]
Thanks for the repro, I'll take a look.

**Comment by sagacity** [comment]
This fiddle now works:
http://jsfiddle.net/pbvtH/11/

You were creating your own observables in the `Employee` constructor and then updating them, instead of letting the mapping plugin create them for you. This workaround now maps the `Employee` using the mapping plugin.

However, your approach should have worked properly as well, but for some reason didn't (so I still need to investigate some more).

**Comment by tuscland** [comment]
Hi Roy,

Thanks for looking into the problem. So that's interesting, I wasn't aware of this mapping feature ; now, having looked at the docs I can see this is how things are supposed to work.

Unfortunately, the workaround is not practical to me, because I need to specify my own observables (for validation purposes, numeric/date observables, etc.). If you have any suggestion regarding this, I'll be glad to hear.

**Comment by sagacity** [comment]
I just pushed a fix for the underlying problem. Your existing fiddle ("/9") should now also work correctly. Can you confirm?

**Comment by tuscland** [comment]
Awesome, the fix works, thank you Roy!
