### ISSUE TITLE
Call to debugger() in minified version

### ISSUE THREAD

**Issue by tuscland** [SteveSanderson/knockout.mapping#89]
In version `1ddb6bce5c125b777775cfe68a8856523f9a3068`
In knockout.mapping-latest.debug.js, line 622 there is call to `debugger()`.
This call also happens in the minified version, which is a bit annoying when running the javascript console with production code.

**Comment by sagacity** [comment]
Ah, that got left in, sorry! This is fixed in 104753a7f4b0080e8642b2f66815f25acd122219.

**Comment by tuscland** [comment]
Thank you Roy.
