### ISSUE TITLE
Updating throttled observable

### ISSUE THREAD

**Issue by molnarg** [SteveSanderson/knockout.mapping#99]
I've run into the following issue.

When running this, I get the expected result, the observable is updated and the subscriber function fires when the update happens:

``` javascript
var a = { x : ko.observable() };
a.x.subscribe(function(value){console.log(value)}); 
a.x(1); a.x(2); a.x(9);            // console: 1, 2, 9

ko.mapping.fromJS({x:3}, {}, a);   // console: 3
console.log(a.x())                 // console: 3
```

But when trying the same thing with a throttle extender, the value is not written to the observable:

``` javascript
var a = { x : ko.observable().extend({throttle:1}) };
a.x.subscribe(function(value){console.log(value)}); 
a.x(1); a.x(2); a.x(9);            // console: 9

ko.mapping.fromJS({x:3}, {}, a);   // console: nothing.
console.log(a.x())                 // console: 9
```

**Comment by molnarg** [comment]
After debugging the code, I can now see what happens.

The write function of the computed observable returned by the throttle extender gets actually called with the correct value at first by the `updateViewModel` function. (at line 379 in the 2.3 release)

But then it gets called again with its original value by the anonymus function passed to `visitPropertiesOrArrayEntries` in `updateViewModel`. (at line 440 in the 2.3 release)

At first the subscribers are not notified because this is the point of the throttle extender. Writing the actual observable is deferred. But then the other write comes in with the old value. When the throttle computed observable actually writes the original observable it writes the last value it gets, the old value. That's why the value of the observable doesn't change.

I still don't know how to fix the issue in the mapping plugin, but I hope this explanation helps someone who does.

**Comment by sagacity** [comment]
Thanks for the detailed analysis, I'll look into it.

**Comment by sagacity** [comment]
This should be fixed now. Can you confirm?
